/* ============================================================
   skillsData.js — Skill-Tree wiki v2.2.6 (liste trackable)
   Layout jeu = liste + panneau détail (pas l'arbre SVG).
   ============================================================ */

/** maxLevels: 1 = on/off ; >1 = niveaux (coûts croissants wiki) */
export const SKILL_NODES = [
  { id:'lucky_strikes', name:'Lucky Strikes', effect:'Pickaxe Crit Chance +5% · Crit Damage +15%', cost:1, sTier:false },
  { id:'bigger_blasts', name:'Bigger Blasts', effect:'Bomb Damage +25%', cost:1 },
  { id:'ore_efficiency', name:'Ore Efficiency', effect:'Double Craft Chance +5%', cost:1 },
  { id:'swing_harder', name:'Swing Harder', effect:'Pickaxe Damage +20%', cost:1 },
  { id:'ingot_intuition', name:'Ingot Intuition', effect:'Pickaxe Bar Cost -10', cost:1 },
  { id:'arsenal', name:'Arsenal Advancement', effect:'Bomb Cap +10 · Bomb Dmg +10% · Free Bomb +1%', cost:3 },
  { id:'all_round', name:'All-Round Bomber', effect:'Bomb Dmg +40% · Recharge +10% · Crit +5%', cost:2 },
  { id:'wait_crits', name:"Wait My Crits Can Crit?", effect:'Pickaxe Super Crit Chance +10%', cost:2 },
  { id:'easy_prog', name:'Easy Progressor', effect:'Floor Clear -10% · PP 1.2x · Sell 1.2x', cost:3 },
  { id:'pp_go_up', name:'PP Go Up', effect:'PP Gain +25% · Exp +25%', cost:2 },
  { id:'gems_chests', name:'Gems & Chests', effect:'Freebie +1 Gem · Relic Chest +1%', cost:2 },
  { id:'super_damage', name:'Super Damage', effect:'Pickaxe +40% · Crit Dmg +20% · Radius +15%', cost:4 },
  { id:'hefty_hammers', name:'Hefty Hammers', effect:'Triple Craft +5% · 10x Craft +1%', cost:3 },
  { id:'relic_rampage', name:'Relic Rampage', effect:'+0.1% Pickaxe Dmg per Relic Chest', cost:3 },
  { id:'just_wait', name:'Just Wait Faster', effect:'Freebie Pack Timer -60s', cost:4 },
  { id:'mech_evo', name:'Mechanical Evolution', effect:'Drone Suit Upgrade Cap +3', cost:7 },
  { id:'chronokeeper', name:'Chronokeeper', effect:'Offline Items/Relics ×2 · Freebie Cap +1 · Bomb Cap +10', cost:5 },
  { id:'gem_bomb', name:'Gem Bomb', effect:'Damage from gems · 3% chance give a gem', cost:5, sTier:true },
  { id:'treasure_hunter', name:'Treasure Hunter', effect:'Freebie Relic Chest +1% · scaling relic chance', cost:7 },
  { id:'demo_expert', name:'Demolition Expert', effect:'Bomb Crit scaling · Super Crit +20% · Free Bomb +3%', cost:5 },
  { id:'wait_super', name:"Wait My Super Crits Can Crit?", effect:'Pickaxe Ultra Crit Chance +20%', cost:5 },
  { id:'auto_bomber', name:'Auto-Bomber', effect:'Auto-fire any bomb every 1.25s', cost:10, sTier:true },
  { id:'perfect_gold', name:'Perfect Gold', effect:'Golden Floor Ore Multiplier +2x', cost:10 },
  { id:'flamboyant', name:'Flamboyant Bombs', effect:'Bomb +150% · Ultra Crit +10% · Cap +5', cost:12 },
  { id:'more_ore', name:'More Ore More Problems', effect:'+2 Ores/screen · Bar Craft -10%', cost:12 },
  { id:'free_price', name:"Free? That's A Great Price", effect:'Freebie -60s · Relic +2% · 5% instant refresh', cost:12, sTier:true },
  { id:'wait_ultra', name:"Wait My Ultra Crits Can Crit?", effect:'Pickaxe +200% · Omega Crit +10%', cost:12 },
  { id:'upgrades_end', name:'Do These Upgrades Ever End', effect:'+1 Cap all Artifacts & Workshop', cost:18 },
  { id:'optical', name:'Optical Phenomenon', effect:'+1% Rainbow Floor Chance', cost:18 },
  { id:'luckier', name:'Have You Tried Getting Luckier?', effect:'Pets level-up +15% · Chest meter 15x', cost:22, unlockOb:17 },
  { id:'stonks', name:'Stonks', effect:'1% +200 Gems / +20 Items / +10 Relics from freebie', cost:22, unlockOb:17, sTier:true },
  { id:'gasoline', name:'Gasoline Guzzler', effect:'Fuel Duration +20% · Coal -10s · Cap +25%', cost:25, unlockOb:18 },
  { id:'wares', name:'I Have Wares, If You Have Coin', effect:'Ore Sell 2.00x · Golden Floor +20%', cost:25, unlockOb:18 },
  { id:'fishing_friends', name:'Fishing With Friends', effect:'Fishing Drones +5 · Power +10% · Fish Multi +3%', cost:[40,50,63], unlockOb:37, maxLevels:3 },
  { id:'veinmorpher', name:"Y'all Got Any More Of Them Veins?", effect:'Unlocks Veinmorpher Bomb', cost:28, unlockOb:19 },
  { id:'rainy_day', name:'Saving For A Rainy Day', effect:'Freebie Cap +2 · Lootbug Cap +2 · Gem cost -1', cost:28, unlockOb:19 },
  { id:'pick_pace', name:"Let's Pick Up The Pace", effect:'Fishing Tick -2s · Double +2% · Triple +1%', cost:[40,50,63], unlockOb:37, maxLevels:3 },
  { id:'friendship_t1', name:'Friendship Ended With Tier 1 Items', effect:'T2 Items +2 · Duration +15% · Notice Fish -10%', cost:[50,63,78], unlockOb:37, maxLevels:3 },
  { id:'whos_asking', name:"Who's Asking For All These Bars?", effect:'Contract Pts +2 · Triple +8% · Refund +1', cost:32, unlockOb:20 },
  { id:'creative_names', name:"I'm Running Out Of Creative Names", effect:'Rainbow Floor +1% · 10x Craft +2% · Bar -10%', cost:32, unlockOb:20 },
  { id:'fish_summon', name:'With This Fish I Summon Two More Fish', effect:'Fish Multi & Shiny per Fish Card', cost:[50,63,78], unlockOb:37, maxLevels:3 },
  { id:'motley', name:'Motley School', effect:'Rod +10% · Dock ticks · Fishing Drones +5', cost:[100,125,156], unlockOb:50, maxLevels:3 },
  { id:'tons_dmg', name:'Tons Of Damage', effect:'Pickaxe ×2 · Ultra Crit +15% · Exp +100%', cost:36, unlockOb:23 },
  { id:'ctrl_f_stars', name:"Ctrl+F 'Stars'", effect:'Follow Stars · Supernova Multi +20%', cost:36, unlockOb:23 },
  { id:'completionist', name:'Completionist Gatekeeper', effect:'Per Legendary Fish: dock/drone/shiny', cost:[100,125,156], unlockOb:50, maxLevels:3 },
  { id:'poly_while', name:'This Is Gonna Take A While..', effect:'Unlocks Polychrome Cards', cost:40, unlockOb:26 },
  { id:'block_bonker', name:'Block Bonker', effect:'Dmg/Stamina per Highest Stage +1%', cost:50, unlockOb:30 },
  { id:'avada', name:"Avada Keda-'Obelisk", effect:'Ability Duration +5s · CD -10s · Instacharge +3%', cost:50, unlockOb:30 },
  { id:'threes_crowd', name:"Three's A Crowd", effect:'+1 Drone', cost:40, unlockOb:26 },
  { id:'poly_power', name:'Polychrome Power', effect:'+0.03x Pickaxe/Sell/Exp per Poly Card', cost:50, unlockOb:26 },
  { id:'auto_prestige', name:"Take it back now y'all", effect:'Unlocks Auto-Prestige', cost:65, unlockOb:30 },
  { id:'please_sir', name:"Please Sir Don't Make Me Prestige Again", effect:'Contract refunds +1 · 10x Contract Chance', cost:[65,81,102], unlockOb:43, maxLevels:3 },
  { id:'lep_legacy', name:"Leprechaun's Legacy", effect:'×1.10 Stars/Vein/Golden Floor/Bomb Recharge', cost:45, unlockOb:26 },
  { id:'lootin_bugs', name:"Anyone Up Lootin' They Bugs", effect:'Lootbug Cap +3 · Loot Multi +4% /lvl', cost:[225,281,352], unlockOb:60, maxLevels:3 },
  { id:'insane_vein', name:'Insane In The Vein Gain', effect:'Vein Poly +1x · Rainbow Vein +6%', cost:[70,88,109], unlockOb:44, maxLevels:3 },
  { id:'call_void', name:'Call Of The Void', effect:'Void Portal Multi +5% · Void Grade Cap +4 /lvl', cost:[250,313,391], unlockOb:60, maxLevels:3 },
  { id:'flaming_veins', name:'Flaming Veins', effect:'Unlocks Infernal Vein Cards', cost:500, unlockOb:60 },
  { id:'ctrl_c_stars', name:'Ctrl+C Ctrl+V Stars', effect:'Orion Cap +2 · Supernova +6% · 10x Chance +1%', cost:[75,94,117], unlockOb:45, maxLevels:3 },
  { id:'pond_yield', name:'Pond Yield', effect:'Golden Frog Multi +0.001x per caught', cost:750, unlockOb:60 },
  { id:'frog_frenzy', name:'Frog Frenzy', effect:'Frogger Cap +2 · Triple Frog +1% · Cap +1', cost:[750,938,1172], unlockOb:62, maxLevels:3 },
  { id:'astral_forge', name:'Astral Forge', effect:'Unlocks Infernal Star Cards', cost:500, unlockOb:60 },
  { id:'stars_mining', name:'Why Are There Stars In My Mining Game', effect:'Novagiant +5% · SGI +1% · Capricorn/Gemini caps', cost:[950,1188,1484], unlockOb:64, maxLevels:3 },
  { id:'ob_mincer', name:'Idle Obelisk Mincer', effect:'Pickaxe 2.50x · Scorpio +5 · Contract/Workshop caps', cost:2000, unlockOb:64 },
  { id:'buried_it', name:'I Buried It Here (55.251920, -6.483423)', effect:'Golden Void +2% · Galactic Floor +2% · Chain Cap +5', cost:[950,1188,1484], unlockOb:64, maxLevels:3 },
  { id:'portal_schmortal', name:'Portal Schmortal', effect:'Galactic Portal +1% · Void +5% · Void Cap +20', cost:12345, unlockOb:70 },
  { id:'yanille', name:'Straight Outta Yanille', effect:'Arcanist Mana +10% · Essence Shiny/Brittle +1%', cost:34567, unlockOb:71 },
  { id:'mess_bull', name:'Mess With The Bull', effect:'Minotaur Cap +3 · Galactic Portal +10% · Prismatic +3%', cost:23456, unlockOb:70 },
  { id:'fronks', name:'Fronks', effect:'Massive Lootfrog Chance +2%', cost:99999, unlockOb:72 },
];

export function skillMaxLevels(s) {
  return s.maxLevels || (Array.isArray(s.cost) ? s.cost.length : 1);
}
